name: WEMEET Backend Pipeline

on:
  push:
    branches:
      - main
    paths:
      - src/main/java/com/server/wordwaves/**
      - Dockerfile
  pull_request:
    branches:
      - main
    paths:
      - src/main/java/com/server/wordwaves/**
      - Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Make mvnw executable
        run: chmod +x ./mvnw

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

      - name: Build Docker image
        run: docker build -t quan0204/wordwaves-server:latest .

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push quan0204/wordwaves-server:latest

